server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: PrefixPath
          args:
            prefix: /api
        - name: RewritePath
          args:
            regexp: /api/(?<path>.*)
            replacement: /${path}
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**